frontend/views/parsers.py
from flask import Blueprint, request, render_template, flash, url_for
from werkzeug.utils import redirect

from src.services.handbooks import HandbookService
from src.services.parsers import ParserService
from views.middlewares.auth import authorization_required

parsers = Blueprint("parsers", __name__)


@parsers.route("/")
@authorization_required
def index(auth_token):
    return render_template("parsers/index.html")


@parsers.route("/available_platforms")
@authorization_required
def available_platforms(auth_token):
    data, errors = ParserService.get_available_platforms(auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    maps = data['maps']
    return render_template("parsers/available_platforms.html", maps=maps)


@parsers.route('/order')
@authorization_required
def make_order(auth_token):
    data, errors = ParserService.get_available_platforms(auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    maps = data['maps']
    return render_template("parsers/make_order.html", maps=maps)


@parsers.route("/order/maps/<map_name>", methods=["GET", "POST"])
@authorization_required
def make_order_maps(auth_token, map_name):
    if request.method == "POST":
        form = request.form
        data = {
            "data": {
                "city": form.get("city"),
                "organisation": form.get("organisation"),
            },
            "parser": {
                "name": map_name,
                "type": "maps",
            }
        }
        data, errors = ParserService.make_order(data=data, x_token=auth_token)
        if errors:
            flash(errors)
            return render_template("parsers/make_order_maps.html", map_name=map_name)

        if data.get("status"):
            flash_message = "Заказ успешно создан."
        else:
            flash_message = 'Ошибка при создании заказа.'
        flash(flash_message)
        return redirect(url_for("parsers.index"))
    cities, errors = HandbookService.get_cities()
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    return render_template("parsers/make_order_maps.html", map_name=map_name, cities=cities)


@parsers.route('/orders', methods=["GET"])
@authorization_required
def orders(auth_token):
    response, errors = ParserService.get_orders(x_token=auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    return render_template("parsers/orders.html", orders=response)


@parsers.route("/orders/<order_id>", methods=["GET"])
@authorization_required
def order_detail(auth_token, order_id):
    response, errors = ParserService.get_detail_by_id(order_id, x_token=auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    return render_template("parsers/detail_order.html", order=response)


@parsers.route("/orders/<order_id>/delete", methods=["POST"])
@authorization_required
def delete_order(auth_token, order_id):
    response, errors = ParserService.delete_order(order_id, x_token=auth_token)
    if errors:
        flash(errors)
    return redirect(url_for("parsers.orders"))


@parsers.route('/examples', methods=["GET"])
def examples():
    response, errors = HandbookService.get_examples()
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    return render_template("parsers/examples.html", data=response)

frontend/templates/parsers/available_platforms.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    {% for map in maps %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{ url_for('static', filename=map.image_link) }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ map.name }}</h5>
                    <p class="card-text">
                        {% if map.correct %}
                            <span class="text-success">Парсер протестирован!</span>
                        {% else %}
                            <span class="text-danger">Парсер работает в тестовом режиме!</span>
                        {% endif %}
                    </p>
                    <a href="{{ map.link }}" class="btn btn-info m-2">Перейти на сайт</a>
                    <a href="/order/maps/{{ map.name }}" class="btn btn-info m-2">Попробовать</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

frontend/templates/parsers/detail_order.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
        <div class="order">
            <hr>
            <h5>Тип парсинга: {{ order.data.parser.type }}. {{ order.data.parser.name }}</h5>
            <h5>Город: {{ order.data.data.city }}. Организация: {{ order.data.data.organisation }}</h5>
            <h5>Дата: {{ order.created_at.split("T")[0] }}</h5>
            {% if order.result %}
            <h6 class="text-success">Успешно!</h6>
            {% else %}
            <h6 class="text-warning">В процессе парсинга возникла ошибка!</h6>
            {% endif %}
            <div class="row">
                <div class="d-flex flex-row-reverse">
                    {% if order.result %}
                        <a class="btn btn-success m-1" href="/{{ order.result.html_filename }}" download>
                            Скачать файл
                        </a>
                    {% endif %}
                    <div class="m-1">
                        <form action="{{ url_for('parsers.delete_order', order_id=order.order_id) }}" method="post" onsubmit="return confirm('Are you want to delete this order?');">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <hr>
    <div class="results">
        <h4>Результаты</h4>
        {% for address, reviews in order.result.data.items() %}
            <div class="review mt-5">
                {% for review in reviews %}
                <div class="col-md-12 mb-3">
                    <h5 class="mt-3">
                        Адрес: {{ address }}
                    </h5>
                    <h5 class="mt-3">
                        Имя: {{ review.name }}
                    </h5>
                    <h5 class="mt-3">
                        Дата: {{ review.date }}
                    </h5>
                    <h5 class="mt-3">
                        Оценка: {{ review.grade }}
                    </h5>
                    <h5 class="mt-3">
                        Текст: {{ review.text_review }}
                    </h5>
                </div>
                <hr/>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

frontend/templates/parsers/examples.html
{% extends 'base.html' %}

{% block content %}
{% if data.type == "maps" %}
<div class="row">
    <div class="title">
        <h3>Карты</h3>
    </div>
    <hr>
    <div class="col-md-4 d-flex justify-content-center align-items-center">
        <h5 class="">JSON</h5>
    </div>
    <div class="col-md-8">
        <div class="bg-light">
<pre>
<code>
    { {% for address, reviews in data.examples.json.data.items() %}
        '{{address}}': [{% for review in reviews %}
            { {% for key, value in review.items() %}
                '{{key}}': '{{value}}'{% endfor %}
            }
        {% endfor %}]
    {% endfor %} }
</code>
</pre>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 d-flex justify-content-center align-items-center">
        <h5 class="">HTML</h5>
    </div>
    <div class="col-md-8">
        <div class="bg-light">
<pre>
<code>
{{ data.examples.html.data.review }}
</code>
</pre>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

frontend/templates/parsers/index.html
{% extends 'base.html' %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
<script type="text/javascript">
    function disableF5(e) { if ((e.which || e.keyCode) == 116 || (e.which || e.keyCode) == 82) e.preventDefault(); };


    $(document).ready(function () {

        $(document).on("keydown", disableF5);

        window.onbeforeunload = function(event) {
            event.preventDefault();
            console.log('hello');
            window.close();
        }
    });
</script>
{% endblock content %}

frontend/templates/parsers/make_order.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="maps">
        <h5>Парсинг отзывов об организации с карт</h5>
        <hr class="p-1 rounded">
        {% for map in maps %}
            <div class="row">
                <div class="col-md-3">
                    <img class="img w-100" src="{{url_for('static', filename=map.image_link) }}" alt="image">
                </div>
                <div class="col-md-4">
                    <h5>{{ map.name }}</h5>
                </div>
                <div class="col-md-5 d-flex flex-row-reverse">
                    <a class="btn btn-info m-5" href="/order/maps/{{ map.name }}">Выбрать</a>
                </div>
                <hr>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

frontend/templates/parsers/make_order_maps.html
{% extends 'base.html' %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="d-flex justify-content-center title">
        <h4>Заказ на парсинг отзывов с карты</h4>
    </div>
    <div class="col-md-4">
        <form action="{{ url_for('parsers.make_order_maps', map_name=map_name) }}" method="post" id="formOrder">
            <div class="form-group">
                <label for="InputCity">Город</label><br>
                <input name="city" value="Выберите город" required hidden id="InputCity">
                <input id="InputCityButton" value="Выберите город" type="button" class="btn btn-primary"
                       data-bs-toggle="modal" data-bs-target="#exampleModal" placeholder="Выберите город">
            </div>
            <div class="form-group">
                <label for="exampleInputOrganisation">Организация</label>
                <input name="organisation" required type="text" class="form-control" id="exampleInputOrganisation"
                       placeholder="Введите организацию" minlength="3" maxlength="50" pattern="^[A-ZА-Я][\s\S]*$">
            </div>
            <button type="submit" class="btn btn-primary mt-3">Подтвердить</button>
        </form>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for city in cities %}
                    <input onclick="changeCity('{{city}}');" type="button" class="city_input btn btn-light" value="{{city}}">
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>
    function changeCity(value){
        input_city = document.getElementById('InputCity');
        input_city.value = value;
        input_city = document.getElementById('InputCityButton');
        input_city.value = value;

        $('#exampleModal').modal('hide');
    }

    $(document).ready(function () {

        $('#formOrder').submit(function(event){
            event.preventDefault();
            if ($("#InputCityButton").val() == "Выберите город"){
                alert("Выберите город!");
                return false;
            }
            this.submit();
        });

        $('#exampleInputOrganisation').on('input invalid', function() {
            this.setCustomValidity('')
            if (this.validity.valueMissing) {
              this.setCustomValidity("Нет значения")
            }
            if (this.validity.typeMismatch) {
              this.setCustomValidity("Не соответствует типу")
            }
            if (this.validity.patternMismatch) {
              this.setCustomValidity("Введите название организации с заглавной буквы. Длина должна быть больше 3 символов")
            }
        });

    });

</script>
{% endblock content %}

frontend/templates/parsers/orders.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    {% for order in orders %}
        <div class="order">
            <hr>
            <h5>Тип парсинга: {{ order.data.parser.type }}. {{ order.data.parser.name }}</h5>
            <h5>Город: {{ order.data.data.city }}. Организация: {{ order.data.data.organisation }}</h5>
            <h5>Дата: {{ order.created_at.split("T")[0] }}</h5>
            {% if order.result %}
            <h6 class="text-success">Успешно!</h6>
            {% else %}
            <h6 class="text-warning">В процессе парсинга возникла ошибка!</h6>
            {% endif %}
            <div class="row">
                <div class="d-flex flex-row-reverse">
                    {% if order.result %}
                        <a class="btn btn-info m-1" href="{{ url_for('parsers.order_detail', order_id=order.order_id) }}">Посмотреть результаты</a>
                        <div class="dropdown m-1">
                            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Скачать файл
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="btn btn-light m-1" href="/{{ order.result.html_filename }}" download>
                                    HTML
                                </a>
                                <a class="btn btn-light m-1" href="/{{ order.result.json_filename }}" download>
                                    JSON
                                </a>
                            </div>
                        </div>

                    {% endif %}
                    <div class="m-1">
                        <form action="{{ url_for('parsers.delete_order', order_id=order.order_id) }}" method="post" onsubmit="return confirm('Are you want to delete this order?')">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}