frontend/views/account.py
from flask import Blueprint, request, url_for, render_template, flash, session
from werkzeug.utils import redirect

from src.services.account import AccountService
from views.middlewares.auth import authorization_required

account = Blueprint("account", __name__)


@account.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        data = {
            "email": request.form.get("email"),
            "password": request.form.get("password"),
            "repeat_password": request.form.get("repeat_password")
        }
        response, errors = AccountService.signup(data=data)
        if errors:
            flash(errors)
            return redirect(url_for("account.signup"))
        return redirect(url_for("account.login"))
    return render_template("account/signup.html")


@account.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        data = {
            "email": request.form.get("email"),
            "password": request.form.get("password")
        }
        response, errors = AccountService.login(data=data)
        if errors:
            flash(errors)
            return redirect(url_for("account.login"))

        session['x_token'] = response['access_token']
        return redirect(url_for("parsers.index"))

    return render_template("account/login.html")


@account.route("/logout", methods=["POST"])
@authorization_required
def logout(auth_token):
    if request.method == "POST":
        session.pop("x_token")
    return redirect(url_for("account.login"))


@account.route('/confirm_email/<account_id>', methods=["GET"])
def confirm_email(account_id):
    _, errors = AccountService.confirm_email(account_id)
    flash_message = "Аккаунт успешно подтвержден"
    if errors:
        flash_message = errors
    flash(flash_message)
    if session.get('x_token'):
        return redirect(url_for("account.personal_office"))
    return redirect(url_for("account.login"))


@account.route('/forgot_password', methods=["GET", "POST"])
def forgot_password():
    if request.method == 'POST':
        data = {
            'email': request.form.get("email")
        }
        _, errors = AccountService.forgot_password(data=data)
        if errors:
            flash(errors)
            return render_template("account/forgot_password.html")
        flash("Ссылка успешно отправлена")
        return redirect(url_for("account.login"))
    return render_template("account/forgot_password.html")


@account.route("/reset_password/<account_id>", methods=["GET", "POST"])
def reset_password(account_id):
    if request.method == "POST":
        data = {
            "password": request.form.get("password"),
            "repeat_password": request.form.get("repeat_password"),
            "email": request.form.get("email")
        }
        _, errors = AccountService.reset_password(account_id, data=data)
        if errors:
            flash(errors)
            return render_template("account/reset_password.html")
        flash("Пароль успешно обновлен")
        return redirect(url_for("account.login"))
    return render_template("account/reset_password.html", account_id=account_id)


@account.route('/personal_office', methods=["GET", "POST"])
@authorization_required
def personal_office(auth_token):
    detail_account, errors = AccountService.get_detail(x_token=auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("parsers.index"))
    return render_template("account/personal_office.html", account=detail_account)


@account.route('/personal_office/update_account', methods=['POST'])
@authorization_required
def update_account_info(auth_token):
    detail_account, errors = AccountService.get_detail(x_token=auth_token)
    if errors:
        flash(errors)
        return redirect(url_for("account.personal_office"))
    data = {
        "email": request.form.get('email'),
    }
    if request.form.get("first_name") != detail_account.get('first_name'):
        data['first_name'] = request.form.get("first_name")
    if request.form.get("last_name") != detail_account.get("last_name"):
        data['last_name'] = request.form.get("last_name")

    _, errors = AccountService.update_account(data=data, x_token=auth_token)
    if errors:
        flash(errors)
    return redirect(url_for("account.personal_office"))


@account.route('/personal_office/update_password', methods=["POST"])
@authorization_required
def reset_password_auth(auth_token):
    data = {
        'old_password': request.form.get("old_password"),
        "new_password": request.form.get("new_password"),
        "repeat_new_password": request.form.get("repeat_new_password"),
    }

    _, errors = AccountService.update_password(data=data, x_token=auth_token)
    if errors:
        flash(errors)
    return redirect(url_for("account.personal_office"))

frontend/templates/base.html
{% extends 'connect_cdn.html' %}

{% block base_content %}
<body>
{% include 'navbar.html' %}
<div class="container mt-3">
    {% block content %}

    {% endblock content %}
</div>
</body>

{% endblock base_content %}

frontend/templates/connect_cdn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>
{% block base_content %}

{% endblock base_content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</html>

frontend/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container collapse navbar-collapse">
        <a class="navbar-brand" href="{{ url_for('parsers.index') }}">Parsers</a>
        <ul class="navbar-nav me-auto">
            {% for name, link in (
                                    ('Главная', url_for('parsers.index')),
                                    ("Доступные площадки",  url_for('parsers.available_platforms')),
                                    ("Примеры", url_for('parsers.examples')),
                                    ("Сделать заказ", url_for('parsers.make_order'))
                                ) %}
            <li class="nav-item">
                {% if request.path == link %}
                    <a class="nav-link active" href="{{ link }}">{{ name }}</a>
                {% else %}
                    <a class="nav-link" href="{{ link }}">{{ name }}</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        <ul class="navbar-nav ms-auto">
            {% if session['x_token'] %}
            <li class="nav-item">
                {% if request.path == url_for('account.personal_office') %}
                    <a class="nav-link active" href="{{ url_for('account.personal_office') }}">Личный кабинет</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('account.personal_office') }}">Личный кабинет</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <form action="{{ url_for('account.logout') }}" method="post">
                    <button type="submit" class="btn nav-link">Выйти</button>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('account.login') }}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('account.signup') }}">Зарегистрироваться</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>